secrets:
  default_password:
    file: ./secrets/default_password.txt

volumes:
  pgadmin:

networks:
  frontend:
    external: ${DOCKER_PROXY_EXT-true}
    name: ${DOCKER_PROXY_NETWORK-proxy}

services:
  pgadmin4:
    image: dpage/pgadmin4:${IMAGE_TAG}
    container_name: pgadmin
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - frontend
    secrets:
      - default_password
    # Uncomment to expose port on host
    # ports:
    #   - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/default_password
      PGADMIN_DISABLE_POSTFIX: ${DISABLE_POSTFIX}
      PGADMIN_CONFIG_MAIL_SERVER: ${MAIL_SERVER-"'localhost'"}
      PGADMIN_CONFIG_MAIL_PORT: ${MAIL_PORT-25}
      PGADMIN_CONFIG_MAIL_USE_SSL: ${MAIL_USE_SSL-False}
      PGADMIN_CONFIG_MAIL_USE_TLS: ${MAIL_USE_TLS-False}
      PGADMIN_CONFIG_MAIL_USERNAME: ${MAIL_USERNAME-"''"}
      PGADMIN_CONFIG_MAIL_PASSWORD: ${MAIL_PASSWORD-"''"}
      PGADMIN_CONFIG_SECURITY_EMAIL_SENDER: ${SECURITY_EMAIL_SENDER-"'no-reply@localhost'"}